{"name": "test_CredKart_Login_008", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_demo.Test_Credence_002 object at 0x0000025815F31F90>\nsetup = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"e5931faf-d98b-43ab-bfbf-99577e7f4a36\")>\n\n    def test_CredKart_Login_008(self,setup):\n        driver = setup\n        # Go to Url\n        driver.find_element(By.XPATH, \"//input[@id='email']\").send_keys(\"Credencetest@test.com\")\n        driver.find_element(By.XPATH, \"//input[@id='password']\").send_keys(\"Credence@1234\")\n        # password\n        driver.find_element(By.XPATH, \"//button[@type='submit']\").click()\n        try:\n>           driver.find_element(By.XPATH, \"//h2[normalize-space()='CredKart']\")\n\ntest_demo.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:739: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:345: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x00000258152AED50>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"Unable to locate element: //h2[normalize-spac...red/webdriver/Errors.sys.mjs:505:5\\\\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:135:16\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //h2[normalize-space()='CredKart']; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:187:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:505:5\nE       element.find/</<@chrome://remote/content/marionette/element.sys.mjs:135:16\n\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: NoSuchElementException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_demo.Test_Credence_002 object at 0x0000025815F31F90>\nsetup = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"e5931faf-d98b-43ab-bfbf-99577e7f4a36\")>\n\n    def test_CredKart_Login_008(self,setup):\n        driver = setup\n        # Go to Url\n        driver.find_element(By.XPATH, \"//input[@id='email']\").send_keys(\"Credencetest@test.com\")\n        driver.find_element(By.XPATH, \"//input[@id='password']\").send_keys(\"Credence@1234\")\n        # password\n        driver.find_element(By.XPATH, \"//button[@type='submit']\").click()\n        try:\n            driver.find_element(By.XPATH, \"//h2[normalize-space()='CredKart']\")\n            print(\"Login TestCase is Passed\")\n            driver.close()\n            assert True\n        except:\n            print(\"Login TestCase is Failed\")\n            driver.close()\n>           assert False\nE           assert False\n\ntest_demo.py:20: AssertionError"}, "attachments": [{"name": "stdout", "source": "f6c948da-b5f6-483f-8e05-ab7e279f03cd-attachment.txt", "type": "text/plain"}], "start": 1690936106509, "stop": 1690936109070, "uuid": "6f376224-4ad9-4f74-b3f8-f6688a03db25", "historyId": "917ef5f7cb5443fd4a453cae846ec571", "testCaseId": "917ef5f7cb5443fd4a453cae846ec571", "fullName": "test_demo.Test_Credence_002#test_CredKart_Login_008", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "Test_Credence_002"}, {"name": "host", "value": "LAPTOP-F03UFEIF"}, {"name": "thread", "value": "28572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}